# data configuration
data: 'CN'
MAX_SEQ: '[]'


# model initialization
model: "NetDetect"
emb_init: 'Conven'
path: 'total'

use_rnn: true
use_seq_pooling: false
use_path_pooling: true
use_conven_seq: true

fraud_dim: 4
hidden_size: 256
use_noisy: 'reweight'
noise_rate: 0.04
print_param: false
patience: 10

# training settings
lr: 0.00002
num_heads: [4,4]
dropout: 0.7
weight_decay: 0.08
num_epochs: 20
threshold_logitdim: 0.485
device: "cuda:1"
fl_param: [4, 0.08]
tvt_split: [2019,2020]
lr_adjust: [1, 0.9]
valid_epoch: 1
seed: 2020
log_dir: "../../output/{}/results/"

Prob: false