# data configuration
data: 'US'
MAX_SEQ: '[-1,0]'

# model  initialization
model: "NetDetect"
emb_init: 'Conven'
path: 'total'

use_rnn: True
use_seq_pooling: True
use_path_pooling: True
use_conven_seq: True


fraud_dim: 4
hidden_size: 64
use_noisy: 'reweight'
noise_rate: 0.04
print_param: False
patience: 10

# training settings
lr: 0.0002
num_heads: [1]
dropout: 0.7
weight_decay: 0.08
num_epochs: 20
threshold_logitdim: 0.45
device: "cuda:3"
fl_param: [5, 0.028]
tvt_split: [2013,2014]
lr_adjust: [1, 0.9]
valid_epoch: 1
seed: 2031
log_dir: "../../output/{}/results/"

Prob: true