# data configuration
data: 'US'
MAX_SEQ: '[-5,-4,-3]'

# model  initialization
model: "NetDetect"
emb_init: 'Conven'
path: 'total'

use_rnn: True
use_seq_pooling: True
use_path_pooling: True
use_conven_seq: True


fraud_dim: 8
hidden_size: 128
use_noisy: 'reweight'
noise_rate: 0.04
print_param: False
patience: 10

# training settings
lr: 0.00005
num_heads: [4,4]
dropout: 0.7
weight_decay: 0.08
num_epochs: 10
threshold_logitdim: 2
device: "cuda:3"
fl_param: [4, 0.058]
tvt_split: [2013,2014]
lr_adjust: [1, 0.9]
valid_epoch: 1
seed: 2031
log_dir: "../../output/{}/results/"

Prob: true